export enum Color {
  Slate = 'slate',
  Gray = 'gray',
  Zinc = 'zinc',
  Neutral = 'neutral',
  Stone = 'stone',
  Red = 'red',
  Orange = 'orange',
  Amber = 'amber',
  Yellow = 'yellow',
  Lime = 'lime',
  Green = 'green',
  Emerald = 'emerald',
  Teal = 'teal',
  Cyan = 'cyan',
  Sky = 'sky',
  Blue = 'blue',
  Indigo = 'indigo',
  Violet = 'violet',
  Purple = 'purple',
  Fuchsia = 'fuchsia',
  Pink = 'pink',
  Rose = 'rose',
  White = 'white',
  Black = 'black',
  Transparent = 'transparent',
}

export enum Weight {
  _50 = '50',
  _100 = '100',
  _200 = '200',
  _300 = '300',
  _400 = '400',
  _500 = '500',
  _600 = '600',
  _700 = '700',
  _800 = '800',
  _900 = '900',
  _950 = '950',
}

export enum FontSizes {
  ExtraSmall = 'xs',
  Small = 'sm',
  Base = 'base',
  Large = 'lg',
  ExtraLarge = 'xl',
  ExtraLarge2 = '2xl',
  ExtraLarge3 = '3xl',
  ExtraLarge4 = '4xl',
  ExtraLarge5 = '5xl',
  ExtraLarge6 = '6xl',
  ExtraLarge7 = '7xl',
  ExtraLarge8 = '8xl',
  ExtraLarge9 = '9xl',
}
