export default {
  number: 1692816975102,
  firstName: 'Amanda',
  lastName: 'xxxxxx',
  email: 'amanda.xxxxx@xxxxx.co.uk',
  phone: '7814040334',
  birthdate: '',
  status: 'delivered',
  createdAt: '2023-08-23T18:56:15.000Z',
  updatedAt: '2023-09-01T11:56:32.000Z',
  gift: true,
  marketingOptIn: {
    email: true,
    sms: false,
  },
  amounts: {
    tax: 9.28,
    tip: 0,
    discounts: 10,
    serviceFee: 4.99,
    total: 51.24,
  },
  shipments: [
    {
      status: 'delivered',
      retailerName: 'Liquor Barn',
      customerPlacement: 'standard',
      scheduledFor: '',
      amounts: {
        tax: 2.64,
        total: 4.29,
        bottleDeposits: 0,
        deliveryFee: 19.99,
        bagFee: 0,
        storeDiscounts: 0,
        liquidDiscounts: 10,
        tipShare: 0,
        subtotal: 31.97,
      },
      deliveryMethod: {
        type: 'shipping',
        deliveryDetail: {
          provider: '',
          deliveryRequestId: '',
        },
        pickupDetail: {
          name: '',
          phone: '',
        },
        packages: [
          {
            carrier: 'ups',
            trackingUrl: 'https://tracking.reservebar.com/1ZB099D84205487531',
            trackingNumber: '1ZB099D84205487531',
            labelUrl: '',
            status: 'delivered',
            estimateDeliveryDate: '2023-08-30T00:00:00.000Z',
          },
        ],
      },
      items: [
        {
          id: '-117751520',
          quantity: 1,
          price: 10.99,
          productId: '8250',
          amounts: {
            total: 10.99,
            bottleDeposits: 0,
            tax: 0.91,
          },
          variant: {
            name: 'Kenwood Vineyards Sonoma Chardonnay',
            msku: '11121',
            volume: '750ml',
          },
          engraving: false,
          engravingOptions: {
            line1: '',
            line2: '',
            line3: '',
            line4: '',
            image: '',
          },
        },
        {
          id: '-117688935',
          quantity: 1,
          price: 10.99,
          productId: '153986',
          amounts: {
            total: 10.99,
            bottleDeposits: 0,
            tax: 0.91,
          },
          variant: {
            name: 'Deloach Pinot Noir California',
            msku: '28428',
            volume: '750ml',
          },
          engraving: false,
          engravingOptions: {
            line1: '',
            line2: '',
            line3: '',
            line4: '',
            image: '',
          },
        },
        {
          id: '-117833117',
          quantity: 1,
          price: 9.99,
          productId: '291694',
          amounts: {
            total: 9.99,
            bottleDeposits: 0,
            tax: 0.82,
          },
          variant: {
            name: 'Bonterra Organic Rosé',
            msku: '34879',
            volume: '750ml',
          },
          engraving: false,
          engravingOptions: {
            line1: '',
            line2: '',
            line3: '',
            line4: '',
            image: '',
          },
        },
      ],
    },
  ],
  paymentMethods: [
    {
      type: 'credit_card',
      holder: 'Amanda xx',
      brand: 'MasterCard',
      last4: '1234',
      code: '',
    },
  ],
  shippingAddress: {
    address1: '11710 SouthGessner Road',
    address2: 'Unit A',
    city: 'Houston',
    state: 'TX',
    zip: '77064',
    country: 'USA',
    latitude: '29.9408151',
    longitude: '-95.54609529999999',
  },
  billingAddress: {
    address1: '55 Timken Way South',
    address2: '',
    city: 'New York',
    state: '',
    zip: '00000',
    country: 'USA',
  },
  deliveryNotes: '',
  giftDetails: {
    message: 'xxxx',
    phone: '+111111111',
    email: 'amanda.xxxxx@xxxxx.co.uk',
    firstName: 'xxxx Al',
    lastName: 'xxxx ',
  },
};
